#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAproxy so that it send traffic to web-01 and web-02
server_config=\
"
frontend web
       bind *:80
       mode http
       default_backend web_servers
backend web_servers
       balance roundrobin
       server 444496-web-01 54.144.149.14:80 check
       server 444496-web-02 18.209.179.185:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
