#!/usr/bin/bash
# Debugging inorder to find out what's keeping my Ubuntu container's
# Nginx installation from listening on port 80
# Delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. Do that by creating a symbolic link
cd /etc/nginx/sites-enabled/ || exit;
sudo rm default;
sudo ln -s /etc/nginx/sites-available/default default;
sudo service nginx restart
